#+STARTUP: indent

* 线性代数(Liner Algebra)

* 概率论(Probability Theory)
** Chapter One Probability Space (概率空间)
介绍概率论公理体系,引出 *样本空间* 给出概率描述性定义,
古典和几何型中的概率计算方法, 引出事件的 $\sigma$ 域给出概率
的 *公理化定义* 及 *基本性质*
*** 1.1 Sample Space (样本空间)
**** 1.1.1 Random Phenomenon(随机现象)
必然现象, 随机现象
统计规律性:大量试验,观察呈现出的规律性.
_概率论和数理统计_ 是研究随机想象统计规律的一门数学学科.
The research object for _probability statistics_ is
a /random phenomenon/.
**** 1.1.2 Sample Space (样本空间)
***** (Random Experiment)随机试验
  1. 同样条件下,这种试验可重复进行
  2. 试验可能结果不止一个,每次只能出现一种随机结果 (Sample Point)
  3. 随机结果可描述(有限集合,无限集合) (Sample Space)
***** Define Sample Space
  1. Sample Point(样本点) 随机结果的集合的元素(set element)
     $$\omega_1,\omega_2,...,\omega_n$$
  2. Sample Space(样本空间) 随机结果的集合(Set)
     $$\Omega = \{ \omega_1, \omega_2, ... \omega_n \}$$
***** Example 表示抛硬币的正反两面
  正面$\omega_1$,反面$\omega_2$
  样本空间$\Omega = \{\omega_1, \omega_2\}$
  同理一次2枚硬币就右4个样本空间.
***** 排列,组合 从1,2,3,4,5中取数
说明:样本空间由试验方法决定
1. 取2次无次序
   $$C_5^2 = \frac{5 \times 4}{2 \times 1} = 10$$
2. 取2次有次序,不重复(不放回)
   $$A_5^2 = 5 \times 4 = 20$$
3. 取2次右次序,有重复(取出后放回去)
   $$5^2 = 25$$
***** 无限集合样本空间
$$\begin{aligned}
&\Omega\ =\ [\ 0,\ \infty\ ) && life\\
&\Omega\ =\ [0,\ 1] && infty\ sample\ space(0,\ 1)\\
&\Omega\ =\ \{\omega(t):\ \omega(t) \in [0,\ \infty] \} && R\ function\\
\end{aligned}$$
**** 1.1.3 Random Event (随机事件)
***** Define Random Event
$\Omega$ 中具有某种性质的 $\omega$ 构成的子集合 (Subset)
$$Event: A,\ B, \cdots, A_1,\ A_2, \cdots \subset \Omega$$
***** Example What is Random Event
$$\left\{
\begin{aligned}
&\omega_1 = (0,0)\\
&\omega_2 = (0,1)\\
&\omega_3 = (1,0)\\
&\omega_4 = (1,1)\\
&\Omega = \{\omega_1,\omega_2,\omega_3,\omega_4\}
\end{aligned}\\
\left\{
\begin{aligned}
&Event\ A = \{\omega_2,\omega_3,\omega_4\}\\
&Event\ A\ has\ 1
\end{aligned}$$
***** Elementary Event(基本事件)
单一样本点的集合$$A=\{\omega_x\}$$
***** Example 一米,分3段.求样本空间$\Omega$?能组成三角形的事件$A_triangle$?
$$\left\{
\begin{aligned}
&\Omega = \{(x,y):x>0,y>0,x+y<1\}\\
&A_triangle = \{(x,y)\in\Omega:0<x<\frac{1}{2},0<y<\frac{1}{2},\frac{1}{2}<x+y<1\}
\end{aligned}$$
***** 不可能事件$\varnothing$,必然事件$\Omega$
**** 1.1.4 Probability (概率)
***** Define Probability
对于样本空间 $\Omega$ 的每个事件 $A$ , 都有一个实数 $P(A)$,它是事件$A$发生的可能性大小的标量
$$0 \le P(A) \le 1,\quad P(\Omega) = 1, P(A)\ is\ Probability\ of\ Event\ A$$
事件 *概率* 的客观存在性很重要,是固有属性
*频率* 记作: $\mu(A)$ :频率是重复 $n$ 次试验A事件发生的次数 $k(0 \le k \le n), \mu(A) = k/n$
*频率稳定性* 当 $n$ 越来越大, 频率与概率的偏差越小,只是偶尔有较大偏差.
**** Exercises (习题)
***** 1.
$$\left\{\begin{aligned}
&\Omega = \{\omega \in 2^3: 0\ is\ back, 1\ is\ front\}\\
&A = \{\omega \in \Omega: \omega\ has\ 2\ front\}\\
&B = \{\omega \in \Omega: \omega\ has\ 2\ or\ 3 front}\\
\end{aligned}$$
***** 2.
$$\left\{\begin{aligned}
&\Omega = \{a_1,a_2,a_3,b_1,b_2\}\\
&A_0 = \{\omega \in C_3^2: a_1,a_2,a_3\}\\
&A_1 = \{\omega \in (C_3^1,C_2^1) \cup (C_2^1,C_3^1)\}\\
&B = \{\omega \in\ (C_2^1,C_3^1)\}\\
\end{aligned}$$