#+STARTUP: indent

#+STARTUP: latexpreview

#+TITLE: Org to \LaTex

* Introduction
** Install
#+BEGIN_SRC sh
apt install texlive-latex-base
apt install texlive-latex-extra
apt install dvipng dvisvgm
#+END_SRC
** preview
C-c C-x C-l (org-latex-preview)
\#+STARTUP: latexpreview
\#+STARTUP: nolatexpreview
** export
C-c C-e l l (org-latex-export-to-latex)
Export to a LaTeX file with a ‘.tex’ extension. For ‘myfile.org’, Org exports to ‘myfile.tex’, overwriting without warning.

C-c C-e l L (org-latex-export-as-latex)
Export to a temporary buffer. Do not create a file.

C-c C-e l p (org-latex-export-to-pdf)
Export as LaTeX file and convert it to PDF file.

C-c C-e l o
Export as LaTeX file and convert it to PDF, then open the PDF using the default viewer.

M-x org-export-region-as-latex

** subsection 1
hello world!
你好!

** formula
$$  \lim_{x \to \infty} x^2_{22} - \int_{1}^{5}x\mathrm{d}x + \sum_{n=1}^{20} n^{2} = \prod_{j=1}^{3} y_{j}  + \lim_{x \to -2} \frac{x-2}{x} $$

\begin{equation*}\lim_{x \to \infty} x^2_{22} - \int_{1}^{5}x\mathrm{d}x + \sum_{n=1}^{20} n^{2} = \prod_{j=1}^{3} y_{j}  + \lim_{x \to -2} \frac{x-2}{x}\end{equation*}


\begin{equation}                        
% arbitrary environments,
x=\sqrt{b}                              
% even tables, figures
% etc
\end{equation}

* Greek Letter
$$ \alpha \beta \gamma \delta \epsilon \varepsilon \zeta \eta \vartheta \iota
\kappa \lambda \mu \nu \xi o \pi \varpi \rho \varrho \sigma \varsigma \tau \upsilon
\phi \varphi \chi \psi \omega$$
$$ A B E Z H I K M N O P T X \Gamma \Lambda \Delta \Theta \Xi \Pi \Sigma \Upsilon \Phi \Psi \Omega$$
* Math
** Letters
$\varnothing$ $\emptyset$
** Matrix
1. \begin{array}{1} , \end{arrar}
   \begin{matrix} , \end{matrix}
2. \\ 表示换行
3. &  表示列分隔
*** \begin{array}{lrc}
{lrc}表示第一列左对齐，第二列右对齐，第三列中对齐, 必须有几列就设置几列；
$$\begin{array}{lcl}
\nabla \cdot \mathbf{E} &= &\cfrac{\rho}{\varepsilon _0} \\
\nabla \cdot \mathbf{B} &= &0 \\
\nabla \times \mathbf{E} &= &- \cfrac {\partial \mathbf{B}} {\partial t}} \\
\nabla \times \mathbf{B} &= &\mu _0\mathbf{J} + \mu _0\varepsilon_0\cfrac{\partial\mathbf{E}}{\partial t}\\
\end{array}$$

$$\left(\begin{array}{ll}
a & b\\
c & d\\
\end{array}\right)$$

$$\left[\begin{array}{c|c|c}
a & b & c\\ \hline
c & d & e\\ \hline
f & g & h
\end{array}\right]$$

*** \begin{matrix/[p|b|B|v|V]matrix}
\begin{matrix}
a & b \\
c & d
\end{matrix}

\begin{pmatrix}
a & b & c\\ \hline
c & d & d \\
\hdashline
e & f & g
\end{pmatrix}

$$\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}$$

$$\begin{Bmatrix}
a & b \\
c & d
\end{Bmatrix}$$

$$\begin{vmatrix}
a & b \\
c & d
\end{vmatrix}$$

$$\begin{Vmatrix}
a & b \\
c & d
\end{Vmatrix}$$

$$\begin{pmatrix}
a_{00} & \cdots & a_{0n} \\
\vdots & \ddots & \vdots \\
a_{n0} & \cdots & a_{nn}
\end{pmatrix}$$

$$\begin{pmatrix}
a_{00} & \cdots & a_{0n} \\
 & \ddots & \vdots \\
&  & a_{nn}
\end{pmatrix}$$
** Formula
*** 输入有序号的公式 $$...$$ \being{equation}
\begin{equation}\label{equ1}
% comments
x^2 & = & 1
\end{equation}
$$x^n+y^n=z^n \eqno{(1.1.1)}$$

\begin{equation} \label{eq:eps}
    \epsilon > 0
\end{equation}
From (\ref{eq:eps}), we can easily draw a conclusion that $\ldots$
*** 行内公式 $...$
If $a^2=b$ and \( b=2 \), then the solution must be either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].
Add $a$ squared to $b$ squared to get $c$ squared.\\ 
Or, using a more mathematical approach:
$a^2+b^2=c^2$
This comes from my $\heartsuit$.

$n \choose k$ $\ldots$ $x \atop y+2$
*** \begin{displaymath} 较大的数学公式
$$\section{Arrays}
\begin{displaymath}
    \mathbf{X} = 
    \left(\begin{array}{ccc}
    x_{11} & x_{12} & \ldots \\
    x_{21} & x_{22} & \ldots \\ 
    \vdots & \vdots & \ddots
    \end{array} \right)
\end{displaymath}\section{Mass-energy}\begin{displaymath}
\boldmath{E} = mc^2
\end{displaymath}\section{Conditions}\begin{displaymath}
\begin{displaymath}
    y = \left\{ \begin{array}{l|l}
    a & \textrm{if $d>c$}\\
    b+x & \textrm{in the morning}\\
    \hline
    l & \textrm{all day long}
\end{array} \right.
\end{displaymath}\section{Eqnarray}\begin{eqnarray}
  f(x) & = & \cos(x) \\
  f'(x) & = & -\sin(x) \\
  \int_0^x f(y)dy & = & \sin(x) \\
  f(x) & = & not support chinese!中文定理环境 \\
  \newline
  中文字体
\end{eqnarray}\section{Phantom}\begin{displaymath}
        {}^{12}_{\phantom{1}6}\textrm{C}
        \qquad \textrm{versus} \qquad
        {}^{12}_{6}\textrm{C}
    \end{displaymath}$$
*** \begin{math}
\begin{math}
    \sqrt{x^2+y^2}  \\   \newline
    \overline{m+n}  \\  \newline
    \underline{m+n} \newline
    \underbrace{a_1+a_2+\ldots+a_n}_{26} \newline
\vec{a} \cdot \vec{b} = \vec{c} \newline
    \frac{x+y}{x^2 + y^2}
\end{math}
*** Theorem/law
需要宏包：\usepacakge{amsthm}
新定义定理环境：\newtheorem{name}[counter]{text}[section]
name：标识这个环境的关键字（用于编程）
text：真正在文档中打印出来的定理环境的名字
counter：计数器；一般新定义的定理环境会自己用一个新的计数器，但是可以在 counter 中传入其他的定理环境，表示和这个环境共用计数器。
section：定理编号依赖于某个章节层次（比如：定理1.1）
$$\newtheorem{name} [counter] {text} [section]
\section{Definitions}
\newtheorem{law}{Law}
\begin{law}
    Don't hide in the witness box.不支持汉字！
\end{law}$$

$$\begin{theorem}[ggdl]
if $a,b$ edge，and $c$ is edge, then $a^2 + b^2 + c^2.$
\end{theorem}$$


% 中文定理环境
% \indent 为了段前空两格
\newtheorem{theorem}{\indent 定理}[section]
\newtheorem{lemma}[theorem]{\indent 引理}
\newtheorem{proposition}[theorem]{\indent 命题}
\newtheorem{corollary}[theorem]{\indent 推论}
\newtheorem{definition}{\indent 定义}[section]
\newtheorem{example}{\indent 例}[section]
\newtheorem{remark}{\indent 注}[section]
\newenvironment{solution}{\begin{proof}[\indent\bf 解]}{\end{proof}}
\renewcommand{\proofname}{\indent\bf 证明}

% % English theorem environment
% \newtheorem{theorem}{Theorem}[section]
% \newtheorem{lemma}[theorem]{Lemma}
% \newtheorem{proposition}[theorem]{Proposition}
% \newtheorem{corollary}[theorem]{Corollary}
% \newtheorem{definition}{Definition}[section]
% \newtheorem{remark}{Remark}[section]
% \newtheorem{example}{Example}[section]
% \newenvironment{solution}{\begin{proof}[Solution]}{\end{proof}}
* Run cpp code
#+BEGIN_SRC cpp
  #include <iostream>
  #include <Eigen/Eigen>
  int main(){
    std::cout << "Eigen example" << std::endl;
    Eigen::MatrixXf matrix1(3, 4);
    matrix1 = Eigen::MatrixXf::Zero(3, 4);
    std::cout<< matrix1 << std::endl;
  }

  // Ctrl+c Ctrl+c
  // run the cpp code
#+END_SRC

#+RESULTS:
| Eigen | example |   |   |
|     0 |       0 | 0 | 0 |
|     0 |       0 | 0 | 0 |
|     0 |       0 | 0 | 0 |

* www
https://blog.csdn.net/ShadyPi/article/details/83049219?utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control
https://blog.csdn.net/anscor/article/details/80878285?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control
* test
| test | 纵纹  | 中文字   | hah   |
| jk   | kjfel | kjfel    | kfjel |
|      |       | 对齐中文 |       |
