#+STARTUP: indent
#+STARTUP: latexpreview

#+TITLE: Org to \LaTex

* Introduction
** preview
C-c C-x C-l (org-latex-preview)
\#+STARTUP: latexpreview
\#+STARTUP: nolatexpreview
** export
C-c C-e l l (org-latex-export-to-latex)
Export to a LaTeX file with a ‘.tex’ extension. For ‘myfile.org’, Org exports to ‘myfile.tex’, overwriting without warning.

C-c C-e l L (org-latex-export-as-latex)
Export to a temporary buffer. Do not create a file.

C-c C-e l p (org-latex-export-to-pdf)
Export as LaTeX file and convert it to PDF file.

C-c C-e l o
Export as LaTeX file and convert it to PDF, then open the PDF using the default viewer.

M-x org-export-region-as-latex

** subsection 1
hello world!
你好!

** formula
$$  \lim_{x \to \infty} x^2_{22} - \int_{1}^{5}x\mathrm{d}x + \sum_{n=1}^{20} n^{2} = \prod_{j=1}^{3} y_{j}  + \lim_{x \to -2} \frac{x-2}{x} $$

\begin{equation}                        
% arbitrary environments,
x=\sqrt{b}                              
% even tables, figures
% etc
\end{equation}

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].

* Greek Letter
$$ \alpha \beta \gamma \delta \epsilon \varepsilon \zeta \eta \vartheta \iota
\kappa \lambda \mu \nu \xi o \pi \varpi \rho \varrho \sigma \varsigma \tau \upsilon
\phi \varphi \chi \psi \omega$$
$$ A B E Z H I K M N O P T X \Gamma \Lambda \Delta \Theta \Xi \Pi \Sigma \Upsilon \Phi \Psi \Omega$$
* Math
$\varnothing$ $\emptyset$
* www
https://blog.csdn.net/ShadyPi/article/details/83049219?utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control
https://blog.csdn.net/anscor/article/details/80878285?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control
